services:
  web:
    build: .
    image: scool
    read_only: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: src
        target: /var/www/html
      - type: bind
        source: ../scool_user_data
        target: /var/www/user_data
      - type: tmpfs
        target: /var/run/apache2
        tmpfs:
          size: 25000000
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 25000000
    ports:
      - "443:443"
#    logging:
#      driver: "awslogs"
#      options:
#        awslogs-region: "us-west-2"
#        awslogs-group: "/apps/SCOOL-App"
#        awslogs-stream: "web"
#    restart: always

  lti:
    build: ../scool_lti
    image: scool_lti
    read_only: true
    env_file:
      - ../scool_lti/.env
#    logging:
#      driver: "awslogs"
#      options:
#        awslogs-region: "us-west-2"
#        awslogs-group: "/apps/SCOOL-App"
#        awslogs-stream: "api"
#    restart: always
