services:
  composer-updates:
    image: composer:2
    volumes:
      - type: bind
        source: ./
        target: /app
    entrypoint:
      - /bin/bash
      - -c
      - |
        cd /app
        composer --ignore-platform-req=ext-pgsql update
