services:
  scool:
    build: .
    image: scool
    env_file:
      - .env
    volumes:
      - type: bind
        source: src
        target: /var/www/html
      - type: bind
        source: ../scool_user_data
        target: /var/www/user_data
    networks:
      - scool_net
    ports:
      - "443:443"
#    logging:
#      driver: "awslogs"
#      options:
#        awslogs-region: "us-west-2"
#        awslogs-group: "/apps/SCOOL-App"
#        awslogs-stream: "web"
#    restart: always

  scool_lti:
    build: ../scool_lti
    image: scool_lti
    env_file:
      - ../scool_lti/.env
    networks:
      - scool_net
    extra_hosts:
      - "canvas.docker:10.20.95.27"
#    logging:
#      driver: "awslogs"
#      options:
#        awslogs-region: "us-west-2"
#        awslogs-group: "/apps/SCOOL-App"
#        awslogs-stream: "api"
#    restart: always

networks:
  scool_net:
